import { and, asc, count, eq, gte, ilike, lte, or, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import type { Pool } from "pg";
import type {
  Asset, AssetAuditEntry, AssetBounds, AssetDispatchReference, AssetEvidence, AssetInspection, AssetLocation, AssetMaintenance,
  AssetRelation, AssetSearchInput, AssetSearchResult, AssetTelemetry, AssetVersionSnapshot,
} from "../domain/asset.js";
import { codeConflictError } from "../domain/asset.js";
import type { AssetRepository, AssetUpdateResult } from "../application/assetRepository.js";
import { assetAuditLog, assetEvidence, assetEventOutbox, assetLocations, assetVersions, assets } from "./schema.js";
import { assetInspections } from "./inspectionSchema.js";
import { assetMaintenance } from "./maintenanceSchema.js";
import { assetRelations } from "./relationSchema.js";
import { assetDispatchReferences } from "./dispatchReferenceSchema.js";
import { assetTelemetry } from "./telemetrySchema.js";

function isTenantCodeConflict(error: unknown): boolean { if (!error || typeof error !== "object") return false; const candidate = error as { code?: string; constraint?: string }; return candidate.code === "23505" && candidate.constraint === "assets_tenant_code_unique"; }
function toAsset(row: typeof assets.$inferSelect): Asset { return { id: row.id, tenantId: row.tenantId, code: row.code, name: row.name, assetType: row.assetType, status: row.status, technicalData: structuredClone(row.technicalData), version: row.version, createdAt: row.createdAt, createdBy: row.createdBy, updatedAt: row.updatedAt, updatedBy: row.updatedBy }; }
function toSnapshot(row: typeof assetVersions.$inferSelect): AssetVersionSnapshot { return { tenantId: row.tenantId, assetId: row.assetId, version: row.version, code: row.code, name: row.name, assetType: row.assetType, status: row.status, technicalData: structuredClone(row.technicalData), changedAt: row.changedAt, changedBy: row.changedBy, reason: row.reason, origin: row.origin, correlationId: row.correlationId }; }
function toLocation(row: typeof assetLocations.$inferSelect): AssetLocation { return { tenantId: row.tenantId, assetId: row.assetId, latitude: row.latitude, longitude: row.longitude, source: row.source, updatedAt: row.updatedAt, updatedBy: row.updatedBy, correlationId: row.correlationId }; }
function toEvidence(row: typeof assetEvidence.$inferSelect): AssetEvidence { return { id: row.id, tenantId: row.tenantId, assetId: row.assetId, kind: row.kind as AssetEvidence["kind"], fileName: row.fileName, mediaType: row.mediaType as AssetEvidence["mediaType"], sizeBytes: row.sizeBytes, storageKey: row.storageKey, sha256: row.sha256, source: row.source, ...(row.signatureReference ? { signatureReference: row.signatureReference } : {}), createdAt: row.createdAt, createdBy: row.createdBy, correlationId: row.correlationId, valid: row.valid }; }
function toInspection(row: typeof assetInspections.$inferSelect): AssetInspection { return { id: row.id, tenantId: row.tenantId, assetId: row.assetId, checklistReference: row.checklistReference, responses: structuredClone(row.responses), result: row.result, status: "finalized", source: row.source, ...(row.latitude !== null && row.longitude !== null ? { location: { latitude: row.latitude, longitude: row.longitude } } : {}), evidenceIds: [...row.evidenceIds], createdAt: row.createdAt, createdBy: row.createdBy, correlationId: row.correlationId }; }
function toMaintenance(row: typeof assetMaintenance.$inferSelect): AssetMaintenance { return { id: row.id, tenantId: row.tenantId, assetId: row.assetId, kind: row.kind, description: row.description, parts: structuredClone(row.parts), costs: structuredClone(row.costs), totalCost: row.totalCost, ...(row.warranty ? { warranty: structuredClone(row.warranty) } : {}), ...(row.links ? { links: structuredClone(row.links) } : {}), source: row.source, createdAt: row.createdAt, createdBy: row.createdBy, correlationId: row.correlationId }; }
function toRelation(row: typeof assetRelations.$inferSelect): AssetRelation { return { id: row.id, tenantId: row.tenantId, assetId: row.assetId, relatedAssetId: row.relatedAssetId, relationType: row.relationType, source: row.source, createdAt: row.createdAt, createdBy: row.createdBy, correlationId: row.correlationId }; }
function toDispatchReference(row: typeof assetDispatchReferences.$inferSelect): AssetDispatchReference { return { id: row.id, tenantId: row.tenantId, assetId: row.assetId, referenceType: row.referenceType as AssetDispatchReference["referenceType"], referenceId: row.referenceId, source: row.source, idempotencyKey: row.idempotencyKey, createdAt: row.createdAt, createdBy: row.createdBy, correlationId: row.correlationId }; }
function toTelemetry(row: typeof assetTelemetry.$inferSelect): AssetTelemetry { return { id: row.id, tenantId: row.tenantId, assetId: row.assetId, eventId: row.eventId, eventVersion: row.eventVersion, eventType: row.eventType, occurredAt: row.occurredAt, source: row.source, relevant: row.relevant, payload: structuredClone(row.payload), receivedAt: row.receivedAt, receivedBy: row.receivedBy, correlationId: row.correlationId }; }
function auditValues(audit: AssetAuditEntry): typeof assetAuditLog.$inferInsert { return { tenantId: audit.tenantId, assetId: audit.assetId, action: audit.action, actorUserId: audit.actorUserId, version: audit.version, correlationId: audit.correlationId, occurredAt: audit.occurredAt }; }
function versionValues(asset: Asset, audit: AssetAuditEntry): typeof assetVersions.$inferInsert { return { tenantId: asset.tenantId, assetId: asset.id, version: asset.version, code: asset.code, name: asset.name, assetType: asset.assetType, status: asset.status, technicalData: structuredClone(asset.technicalData), changedAt: audit.occurredAt, changedBy: audit.actorUserId, reason: audit.reason, origin: audit.origin, correlationId: audit.correlationId }; }
function outboxValues(asset: Asset, audit: AssetAuditEntry): typeof assetEventOutbox.$inferInsert { const eventType = audit.action === "created" ? "asset.created" : "asset.updated"; return { eventId: `asset:${asset.tenantId}:${asset.id}:v${asset.version}:${eventType}`, eventType, eventVersion: "1", tenantId: asset.tenantId, assetId: asset.id, assetVersion: asset.version, correlationId: audit.correlationId, occurredAt: audit.occurredAt, payload: { assetId: asset.id, version: asset.version, code: asset.code, name: asset.name, assetType: asset.assetType, status: asset.status, technicalData: structuredClone(asset.technicalData), changedBy: audit.actorUserId, reason: audit.reason, origin: audit.origin } }; }

export class PostgresAssetRepository implements AssetRepository {
  private readonly db;
  constructor(pool: Pool) { this.db = drizzle(pool, { schema: { assets, assetAuditLog, assetVersions, assetEventOutbox, assetLocations, assetEvidence, assetInspections, assetMaintenance, assetRelations, assetDispatchReferences, assetTelemetry } }); }
  async findById(tenantId: string, assetId: string): Promise<Asset | null> { const rows = await this.db.select().from(assets).where(and(eq(assets.tenantId, tenantId), eq(assets.id, assetId))).limit(1); return rows[0] ? toAsset(rows[0]) : null; }
  async findByCode(tenantId: string, code: string): Promise<Asset | null> { const rows = await this.db.select().from(assets).where(and(eq(assets.tenantId, tenantId), eq(assets.code, code))).limit(1); return rows[0] ? toAsset(rows[0]) : null; }
  async search(tenantId: string, input: AssetSearchInput): Promise<AssetSearchResult> { const conditions = [eq(assets.tenantId, tenantId)]; if (input.assetType) conditions.push(eq(assets.assetType, input.assetType)); if (input.status) conditions.push(eq(assets.status, input.status)); if (input.query) { const pattern = `%${input.query}%`; const textMatch = or(ilike(assets.code, pattern), ilike(assets.name, pattern), ilike(assets.assetType, pattern), ilike(assets.status, pattern), sql`${assets.technicalData}::text ILIKE ${pattern}`); if (textMatch) conditions.push(textMatch); } const where = and(...conditions); const countRows = await this.db.select({ value: count() }).from(assets).where(where); const total = Number(countRows[0]?.value ?? 0); const rows = await this.db.select().from(assets).where(where).orderBy(asc(assets.code), asc(assets.id)).limit(input.pageSize).offset((input.page - 1) * input.pageSize); return { items: rows.map(toAsset), page: input.page, pageSize: input.pageSize, total, totalPages: total === 0 ? 0 : Math.ceil(total / input.pageSize) }; }
  async listHistory(tenantId: string, assetId: string): Promise<AssetVersionSnapshot[]> { const rows = await this.db.select().from(assetVersions).where(and(eq(assetVersions.tenantId, tenantId), eq(assetVersions.assetId, assetId))).orderBy(asc(assetVersions.version)); return rows.map(toSnapshot); }
  async addEvidence(evidence: AssetEvidence): Promise<AssetEvidence> { const rows = await this.db.insert(assetEvidence).values({ id: evidence.id, tenantId: evidence.tenantId, assetId: evidence.assetId, kind: evidence.kind, fileName: evidence.fileName, mediaType: evidence.mediaType, sizeBytes: evidence.sizeBytes, storageKey: evidence.storageKey, sha256: evidence.sha256, source: evidence.source, signatureReference: evidence.signatureReference, createdAt: evidence.createdAt, createdBy: evidence.createdBy, correlationId: evidence.correlationId, valid: evidence.valid }).returning(); if (!rows[0]) throw new Error("Asset evidence insert returned no row"); return toEvidence(rows[0]); }
  async listEvidence(tenantId: string, assetId: string): Promise<AssetEvidence[]> { const rows = await this.db.select().from(assetEvidence).where(and(eq(assetEvidence.tenantId, tenantId), eq(assetEvidence.assetId, assetId))).orderBy(asc(assetEvidence.createdAt), asc(assetEvidence.id)); return rows.map(toEvidence); }
  async addInspection(inspection: AssetInspection): Promise<AssetInspection> { const rows = await this.db.insert(assetInspections).values({ id: inspection.id, tenantId: inspection.tenantId, assetId: inspection.assetId, checklistReference: inspection.checklistReference, responses: inspection.responses, result: inspection.result, status: inspection.status, source: inspection.source, latitude: inspection.location?.latitude, longitude: inspection.location?.longitude, evidenceIds: inspection.evidenceIds, createdAt: inspection.createdAt, createdBy: inspection.createdBy, correlationId: inspection.correlationId }).returning(); if (!rows[0]) throw new Error("Asset inspection insert returned no row"); return toInspection(rows[0]); }
  async listInspections(tenantId: string, assetId: string): Promise<AssetInspection[]> { const rows = await this.db.select().from(assetInspections).where(and(eq(assetInspections.tenantId, tenantId), eq(assetInspections.assetId, assetId))).orderBy(asc(assetInspections.createdAt), asc(assetInspections.id)); return rows.map(toInspection); }
  async addMaintenance(record: AssetMaintenance): Promise<AssetMaintenance> { const rows = await this.db.insert(assetMaintenance).values({ id: record.id, tenantId: record.tenantId, assetId: record.assetId, kind: record.kind, description: record.description, parts: record.parts, costs: record.costs, totalCost: record.totalCost, warranty: record.warranty, links: record.links, source: record.source, createdAt: record.createdAt, createdBy: record.createdBy, correlationId: record.correlationId }).returning(); if (!rows[0]) throw new Error("Asset maintenance insert returned no row"); return toMaintenance(rows[0]); }
  async listMaintenance(tenantId: string, assetId: string): Promise<AssetMaintenance[]> { const rows = await this.db.select().from(assetMaintenance).where(and(eq(assetMaintenance.tenantId, tenantId), eq(assetMaintenance.assetId, assetId))).orderBy(asc(assetMaintenance.createdAt), asc(assetMaintenance.id)); return rows.map(toMaintenance); }
  async addRelation(relation: AssetRelation): Promise<AssetRelation> { const rows = await this.db.insert(assetRelations).values(relation).returning(); if (!rows[0]) throw new Error("Asset relation insert returned no row"); return toRelation(rows[0]); }
  async listRelations(tenantId: string, assetId: string): Promise<AssetRelation[]> { const rows = await this.db.select().from(assetRelations).where(and(eq(assetRelations.tenantId, tenantId), eq(assetRelations.assetId, assetId))).orderBy(asc(assetRelations.createdAt), asc(assetRelations.id)); return rows.map(toRelation); }
  async addDispatchReference(reference: AssetDispatchReference): Promise<AssetDispatchReference> { const rows = await this.db.insert(assetDispatchReferences).values(reference).onConflictDoNothing({ target: [assetDispatchReferences.tenantId, assetDispatchReferences.assetId, assetDispatchReferences.idempotencyKey] }).returning(); if(rows[0])return toDispatchReference(rows[0]); const existing=await this.findDispatchReferenceByIdempotencyKey(reference.tenantId,reference.assetId,reference.idempotencyKey); if(!existing)throw new Error("Dispatch reference idempotency conflict without persisted row"); return existing; }
  async findDispatchReferenceByIdempotencyKey(tenantId:string,assetId:string,idempotencyKey:string):Promise<AssetDispatchReference|null>{const rows=await this.db.select().from(assetDispatchReferences).where(and(eq(assetDispatchReferences.tenantId,tenantId),eq(assetDispatchReferences.assetId,assetId),eq(assetDispatchReferences.idempotencyKey,idempotencyKey))).limit(1);return rows[0]?toDispatchReference(rows[0]):null;}
  async listDispatchReferences(tenantId:string,assetId:string):Promise<AssetDispatchReference[]>{const rows=await this.db.select().from(assetDispatchReferences).where(and(eq(assetDispatchReferences.tenantId,tenantId),eq(assetDispatchReferences.assetId,assetId))).orderBy(asc(assetDispatchReferences.createdAt),asc(assetDispatchReferences.id));return rows.map(toDispatchReference);}
  async addTelemetry(record:AssetTelemetry):Promise<AssetTelemetry>{const rows=await this.db.insert(assetTelemetry).values(record).onConflictDoNothing({target:[assetTelemetry.tenantId,assetTelemetry.assetId,assetTelemetry.eventId]}).returning();if(rows[0])return toTelemetry(rows[0]);const existing=await this.findTelemetryByEventId(record.tenantId,record.assetId,record.eventId);if(!existing)throw new Error("Telemetry idempotency conflict without persisted row");return existing;}
  async findTelemetryByEventId(tenantId:string,assetId:string,eventId:string):Promise<AssetTelemetry|null>{const rows=await this.db.select().from(assetTelemetry).where(and(eq(assetTelemetry.tenantId,tenantId),eq(assetTelemetry.assetId,assetId),eq(assetTelemetry.eventId,eventId))).limit(1);return rows[0]?toTelemetry(rows[0]):null;}
  async listTelemetry(tenantId:string,assetId:string):Promise<AssetTelemetry[]>{const rows=await this.db.select().from(assetTelemetry).where(and(eq(assetTelemetry.tenantId,tenantId),eq(assetTelemetry.assetId,assetId))).orderBy(asc(assetTelemetry.occurredAt),asc(assetTelemetry.eventId));return rows.map(toTelemetry);}
  async setLocation(location: AssetLocation): Promise<AssetLocation> { const rows = await this.db.insert(assetLocations).values(location).onConflictDoUpdate({ target: [assetLocations.tenantId, assetLocations.assetId], set: { latitude: location.latitude, longitude: location.longitude, source: location.source, updatedAt: location.updatedAt, updatedBy: location.updatedBy, correlationId: location.correlationId } }).returning(); if (!rows[0]) throw new Error("Asset location upsert returned no row"); return toLocation(rows[0]); }
  async findLocation(tenantId: string, assetId: string): Promise<AssetLocation | null> { const rows = await this.db.select().from(assetLocations).where(and(eq(assetLocations.tenantId, tenantId), eq(assetLocations.assetId, assetId))).limit(1); return rows[0] ? toLocation(rows[0]) : null; }
  async findLocationsByBounds(tenantId: string, bounds: AssetBounds): Promise<AssetLocation[]> { const rows = await this.db.select().from(assetLocations).where(and(eq(assetLocations.tenantId, tenantId), gte(assetLocations.latitude, bounds.minLatitude), lte(assetLocations.latitude, bounds.maxLatitude), gte(assetLocations.longitude, bounds.minLongitude), lte(assetLocations.longitude, bounds.maxLongitude))).orderBy(asc(assetLocations.assetId)); return rows.map(toLocation); }
  async create(asset: Asset, audit: AssetAuditEntry): Promise<Asset> { try { return await this.db.transaction(async tx => { const rows = await tx.insert(assets).values({ id: asset.id, tenantId: asset.tenantId, code: asset.code, name: asset.name, assetType: asset.assetType, status: asset.status, technicalData: asset.technicalData, version: asset.version, createdAt: asset.createdAt, createdBy: asset.createdBy, updatedAt: asset.updatedAt, updatedBy: asset.updatedBy }).returning(); if (!rows[0]) throw new Error("Asset insert returned no row"); await tx.insert(assetAuditLog).values(auditValues(audit)); await tx.insert(assetVersions).values(versionValues(asset, audit)); await tx.insert(assetEventOutbox).values(outboxValues(asset, audit)); return toAsset(rows[0]); }); } catch (error) { if (isTenantCodeConflict(error)) throw codeConflictError(); throw error; } }
  async update(tenantId: string, assetId: string, expectedVersion: number, nextAsset: Asset, audit: AssetAuditEntry): Promise<AssetUpdateResult> { try { return await this.db.transaction(async tx => { const rows = await tx.update(assets).set({ code: nextAsset.code, name: nextAsset.name, assetType: nextAsset.assetType, status: nextAsset.status, technicalData: nextAsset.technicalData, version: nextAsset.version, updatedAt: nextAsset.updatedAt, updatedBy: nextAsset.updatedBy }).where(and(eq(assets.tenantId, tenantId), eq(assets.id, assetId), eq(assets.version, expectedVersion))).returning(); if (!rows[0]) { const current = await tx.select({ version: assets.version }).from(assets).where(and(eq(assets.tenantId, tenantId), eq(assets.id, assetId))).limit(1); return current[0] ? { status: "version_conflict" as const } : { status: "not_found" as const }; } const persisted = toAsset(rows[0]); await tx.insert(assetAuditLog).values(auditValues(audit)); await tx.insert(assetVersions).values(versionValues(persisted, audit)); await tx.insert(assetEventOutbox).values(outboxValues(persisted, audit)); return { status: "updated" as const, asset: persisted }; }); } catch (error) { if (isTenantCodeConflict(error)) return { status: "code_conflict" }; throw error; } }
}
