import { randomUUID } from "node:crypto";
import { ZodError } from "zod";
import {
  assetBoundsSchema, assetCreateInputSchema, assetEvidenceInputSchema, assetInspectionInputSchema,
  assetLocationInputSchema, assetMaintenanceInputSchema, assetRelationInputSchema, assetRequestContextSchema, assetSearchInputSchema,
  assetUpdateInputSchema, codeConflictError, forbiddenError, notFoundError, validationError, versionConflictError,
  type Asset, type AssetAuditEntry, type AssetBounds, type AssetCreateInput, type AssetEvidence, type AssetEvidenceInput,
  type AssetInspection, type AssetInspectionInput, type AssetLocation, type AssetLocationInput, type AssetMaintenance,
  type AssetMaintenanceInput, type AssetRelation, type AssetRelationInput, type AssetRequestContext, type AssetSearchInput,
  type AssetSearchResult, type AssetTimelineItem, type AssetUpdateInput, type AssetVersionChange, type AssetVersionComparison,
  type AssetVersionSnapshot,
} from "../domain/asset.js";
import type { AssetRepository } from "./assetRepository.js";

export interface AssetServiceDependencies { now?: () => Date; generateId?: () => string; }
const comparableFields = ["code", "name", "assetType", "status", "technicalData"] as const;
function sameValue(left: unknown, right: unknown): boolean { return JSON.stringify(left) === JSON.stringify(right); }
function timelineItemFrom(snapshot: AssetVersionSnapshot): AssetTimelineItem { return { id:`asset:${snapshot.assetId}:v${snapshot.version}`, tenantId:snapshot.tenantId, assetId:snapshot.assetId, type:snapshot.version===1?"asset.created":"asset.updated", occurredAt:new Date(snapshot.changedAt), authorUserId:snapshot.changedBy, source:snapshot.origin, reason:snapshot.reason, correlationId:snapshot.correlationId, version:snapshot.version, data:{code:snapshot.code,name:snapshot.name,assetType:snapshot.assetType,status:snapshot.status,technicalData:structuredClone(snapshot.technicalData)} }; }
function evidenceTimelineItem(e:AssetEvidence):AssetTimelineItem{return{id:`asset:${e.assetId}:evidence:${e.id}`,tenantId:e.tenantId,assetId:e.assetId,type:"asset.evidence.added",occurredAt:new Date(e.createdAt),authorUserId:e.createdBy,source:e.source,reason:e.kind,correlationId:e.correlationId,version:0,data:{evidenceId:e.id,kind:e.kind,fileName:e.fileName,mediaType:e.mediaType,sizeBytes:e.sizeBytes,storageKey:e.storageKey,sha256:e.sha256,signatureReference:e.signatureReference,valid:e.valid}};}
function inspectionTimelineItem(i:AssetInspection):AssetTimelineItem{return{id:`asset:${i.assetId}:inspection:${i.id}`,tenantId:i.tenantId,assetId:i.assetId,type:"asset.inspection.finalized",occurredAt:new Date(i.createdAt),authorUserId:i.createdBy,source:i.source,reason:i.result,correlationId:i.correlationId,version:0,data:{inspectionId:i.id,checklistReference:i.checklistReference,result:i.result,responses:structuredClone(i.responses),evidenceIds:[...i.evidenceIds],location:i.location?{...i.location}:undefined}};}
function maintenanceTimelineItem(m:AssetMaintenance):AssetTimelineItem{return{id:`asset:${m.assetId}:maintenance:${m.id}`,tenantId:m.tenantId,assetId:m.assetId,type:"asset.maintenance.recorded",occurredAt:new Date(m.createdAt),authorUserId:m.createdBy,source:m.source,reason:m.kind,correlationId:m.correlationId,version:0,data:{maintenanceId:m.id,kind:m.kind,description:m.description,parts:structuredClone(m.parts),costs:structuredClone(m.costs),totalCost:m.totalCost,warranty:m.warranty?structuredClone(m.warranty):undefined,links:m.links?structuredClone(m.links):undefined}};}
function relationTimelineItem(r:AssetRelation):AssetTimelineItem{return{id:`asset:${r.assetId}:relation:${r.id}`,tenantId:r.tenantId,assetId:r.assetId,type:"asset.relation.added",occurredAt:new Date(r.createdAt),authorUserId:r.createdBy,source:r.source,reason:r.relationType,correlationId:r.correlationId,version:0,data:{relationId:r.id,relatedAssetId:r.relatedAssetId,relationType:r.relationType}};}

export class AssetService {
  private readonly now:()=>Date; private readonly generateId:()=>string;
  constructor(private readonly repository:AssetRepository,dependencies:AssetServiceDependencies={}){this.now=dependencies.now??(()=>new Date());this.generateId=dependencies.generateId??randomUUID;}
  async create(contextInput:unknown,input:unknown):Promise<Asset>{const c=this.parseContext(contextInput);this.requirePermission(c,"assets:write");const p=this.parseCreate(input);if(await this.repository.findByCode(c.tenantId,p.code))throw codeConflictError();const now=this.now();const a:Asset={id:this.generateId(),tenantId:c.tenantId,code:p.code,name:p.name,assetType:p.assetType,status:p.status,technicalData:structuredClone(p.technicalData),version:1,createdAt:now,createdBy:c.userId,updatedAt:now,updatedBy:c.userId};return this.repository.create(a,this.auditFor(a,c,"created",now,"initial-registration","api"));}
  async search(c0:unknown,input:unknown):Promise<AssetSearchResult>{const c=this.parseContext(c0);this.requirePermission(c,"assets:read");return this.repository.search(c.tenantId,this.parseSearch(input));}
  async get(c0:unknown,id:string):Promise<Asset>{const c=this.parseContext(c0);this.requirePermission(c,"assets:read");const a=await this.repository.findById(c.tenantId,id);if(!a)throw notFoundError();return a;}
  async history(c0:unknown,id:string):Promise<AssetVersionSnapshot[]>{const c=this.parseContext(c0);this.requirePermission(c,"assets:read");if(!await this.repository.findById(c.tenantId,id))throw notFoundError();return this.repository.listHistory(c.tenantId,id);}
  async timeline(c0:unknown,id:string):Promise<AssetTimelineItem[]>{const c=this.parseContext(c0);this.requirePermission(c,"assets:read");if(!await this.repository.findById(c.tenantId,id))throw notFoundError();const[history,evidence,inspections,maintenance,relations]=await Promise.all([this.repository.listHistory(c.tenantId,id),this.repository.listEvidence(c.tenantId,id),this.repository.listInspections(c.tenantId,id),this.repository.listMaintenance(c.tenantId,id),this.repository.listRelations(c.tenantId,id)]);return[...history.map(timelineItemFrom),...evidence.map(evidenceTimelineItem),...inspections.map(inspectionTimelineItem),...maintenance.map(maintenanceTimelineItem),...relations.map(relationTimelineItem)].sort((l,r)=>l.occurredAt.getTime()-r.occurredAt.getTime()||l.version-r.version||l.id.localeCompare(r.id));}
  async addEvidence(c0:unknown,id:string,input:unknown):Promise<AssetEvidence>{const c=this.parseContext(c0);this.requirePermission(c,"assets:write");const p=this.parseEvidence(input);if(!await this.repository.findById(c.tenantId,id))throw notFoundError();return this.repository.addEvidence({id:this.generateId(),tenantId:c.tenantId,assetId:id,kind:p.kind,fileName:p.fileName,mediaType:p.mediaType,sizeBytes:p.sizeBytes,storageKey:p.storageKey,sha256:p.sha256.toLowerCase(),source:p.source,...(p.signatureReference?{signatureReference:p.signatureReference}:{}),createdAt:this.now(),createdBy:c.userId,correlationId:c.correlationId,valid:true});}
  async listEvidence(c0:unknown,id:string):Promise<AssetEvidence[]>{const c=this.parseContext(c0);this.requirePermission(c,"assets:read");if(!await this.repository.findById(c.tenantId,id))throw notFoundError();return this.repository.listEvidence(c.tenantId,id);}
  async recordInspection(c0:unknown,id:string,input:unknown):Promise<AssetInspection>{const c=this.parseContext(c0);this.requirePermission(c,"assets:write");const p=this.parseInspection(input);if(!await this.repository.findById(c.tenantId,id))throw notFoundError();if(p.evidenceIds.length){const own=new Set((await this.repository.listEvidence(c.tenantId,id)).map(e=>e.id));if(p.evidenceIds.some(e=>!own.has(e)))throw validationError();}return this.repository.addInspection({id:this.generateId(),tenantId:c.tenantId,assetId:id,checklistReference:p.checklistReference,responses:structuredClone(p.responses),result:p.result,status:"finalized",source:p.source,...(p.location?{location:{...p.location}}:{}),evidenceIds:[...p.evidenceIds],createdAt:this.now(),createdBy:c.userId,correlationId:c.correlationId});}
  async listInspections(c0:unknown,id:string):Promise<AssetInspection[]>{const c=this.parseContext(c0);this.requirePermission(c,"assets:read");if(!await this.repository.findById(c.tenantId,id))throw notFoundError();return this.repository.listInspections(c.tenantId,id);}
  async recordMaintenance(c0:unknown,id:string,input:unknown):Promise<AssetMaintenance>{const c=this.parseContext(c0);this.requirePermission(c,"assets:write");const p=this.parseMaintenance(input);if(!await this.repository.findById(c.tenantId,id))throw notFoundError();const parts=structuredClone(p.parts);const costs=structuredClone(p.costs);const totalCost=Number((parts.reduce((s,x)=>s+x.quantity*x.unitCost,0)+costs.reduce((s,x)=>s+x.amount,0)).toFixed(2));return this.repository.addMaintenance({id:this.generateId(),tenantId:c.tenantId,assetId:id,kind:p.kind,description:p.description,parts,costs,totalCost,...(p.warranty?{warranty:structuredClone(p.warranty)}:{}),...(p.links?{links:structuredClone(p.links)}:{}),source:p.source,createdAt:this.now(),createdBy:c.userId,correlationId:c.correlationId});}
  async listMaintenance(c0:unknown,id:string):Promise<AssetMaintenance[]>{const c=this.parseContext(c0);this.requirePermission(c,"assets:read");if(!await this.repository.findById(c.tenantId,id))throw notFoundError();return this.repository.listMaintenance(c.tenantId,id);}
  async linkAsset(c0:unknown,id:string,input:unknown):Promise<AssetRelation>{const c=this.parseContext(c0);this.requirePermission(c,"assets:write");const p=this.parseRelation(input);if(p.relatedAssetId===id)throw validationError();if(!await this.repository.findById(c.tenantId,id))throw notFoundError();if(!await this.repository.findById(c.tenantId,p.relatedAssetId))throw notFoundError();return this.repository.addRelation({id:this.generateId(),tenantId:c.tenantId,assetId:id,relatedAssetId:p.relatedAssetId,relationType:p.relationType,source:p.source,createdAt:this.now(),createdBy:c.userId,correlationId:c.correlationId});}
  async listRelatedAssets(c0:unknown,id:string):Promise<AssetRelation[]>{const c=this.parseContext(c0);this.requirePermission(c,"assets:read");if(!await this.repository.findById(c.tenantId,id))throw notFoundError();return this.repository.listRelations(c.tenantId,id);}
  async compare(c0:unknown,id:string,fromVersion:number,toVersion:number):Promise<AssetVersionComparison>{if(!Number.isInteger(fromVersion)||fromVersion<=0||!Number.isInteger(toVersion)||toVersion<=0)throw validationError();const h=await this.history(c0,id);const from=h.find(s=>s.version===fromVersion),to=h.find(s=>s.version===toVersion);if(!from||!to)throw notFoundError();const changes:AssetVersionChange[]=[];for(const f of comparableFields)if(!sameValue(from[f],to[f]))changes.push({field:f,before:structuredClone(from[f]),after:structuredClone(to[f])});return{fromVersion,toVersion,changes};}
  async setLocation(c0:unknown,id:string,input:unknown):Promise<AssetLocation>{const c=this.parseContext(c0);this.requirePermission(c,"assets:write");const p=this.parseLocation(input);if(!await this.repository.findById(c.tenantId,id))throw notFoundError();return this.repository.setLocation({tenantId:c.tenantId,assetId:id,latitude:p.latitude,longitude:p.longitude,source:p.source,updatedAt:this.now(),updatedBy:c.userId,correlationId:c.correlationId});}
  async getLocation(c0:unknown,id:string):Promise<AssetLocation>{const c=this.parseContext(c0);this.requirePermission(c,"assets:read");if(!await this.repository.findById(c.tenantId,id))throw notFoundError();const l=await this.repository.findLocation(c.tenantId,id);if(!l)throw notFoundError();return l;}
  async searchByBounds(c0:unknown,input:unknown):Promise<AssetLocation[]>{const c=this.parseContext(c0);this.requirePermission(c,"assets:read");return this.repository.findLocationsByBounds(c.tenantId,this.parseBounds(input));}
  async update(c0:unknown,id:string,input:unknown):Promise<Asset>{const c=this.parseContext(c0);this.requirePermission(c,"assets:write");const p=this.parseUpdate(input);const cur=await this.repository.findById(c.tenantId,id);if(!cur)throw notFoundError();if(p.code!==undefined&&p.code!==cur.code){const x=await this.repository.findByCode(c.tenantId,p.code);if(x&&x.id!==cur.id)throw codeConflictError();}const now=this.now();const next:Asset={...cur,...(p.code!==undefined?{code:p.code}:{}),...(p.name!==undefined?{name:p.name}:{}),...(p.assetType!==undefined?{assetType:p.assetType}:{}),...(p.status!==undefined?{status:p.status}:{}),...(p.technicalData!==undefined?{technicalData:structuredClone(p.technicalData)}:{}),version:cur.version+1,updatedAt:now,updatedBy:c.userId};const r=await this.repository.update(c.tenantId,id,p.expectedVersion,next,this.auditFor(next,c,"updated",now,p.change?.reason??"technical-update",p.change?.origin??"api"));if(r.status==="not_found")throw notFoundError();if(r.status==="version_conflict")throw versionConflictError();if(r.status==="code_conflict")throw codeConflictError();return r.asset;}
  private parseContext(i:unknown):AssetRequestContext{try{return assetRequestContextSchema.parse(i);}catch(e){if(e instanceof ZodError)throw validationError();throw e;}}
  private parseCreate(i:unknown):AssetCreateInput{try{return assetCreateInputSchema.parse(i);}catch(e){if(e instanceof ZodError)throw validationError();throw e;}}
  private parseUpdate(i:unknown):AssetUpdateInput{try{return assetUpdateInputSchema.parse(i);}catch(e){if(e instanceof ZodError)throw validationError();throw e;}}
  private parseLocation(i:unknown):AssetLocationInput{try{return assetLocationInputSchema.parse(i);}catch(e){if(e instanceof ZodError)throw validationError();throw e;}}
  private parseBounds(i:unknown):AssetBounds{try{return assetBoundsSchema.parse(i);}catch(e){if(e instanceof ZodError)throw validationError();throw e;}}
  private parseSearch(i:unknown):AssetSearchInput{try{return assetSearchInputSchema.parse(i??{});}catch(e){if(e instanceof ZodError)throw validationError();throw e;}}
  private parseEvidence(i:unknown):AssetEvidenceInput{try{return assetEvidenceInputSchema.parse(i);}catch(e){if(e instanceof ZodError)throw validationError();throw e;}}
  private parseInspection(i:unknown):AssetInspectionInput{try{return assetInspectionInputSchema.parse(i);}catch(e){if(e instanceof ZodError)throw validationError();throw e;}}
  private parseMaintenance(i:unknown):AssetMaintenanceInput{try{return assetMaintenanceInputSchema.parse(i);}catch(e){if(e instanceof ZodError)throw validationError();throw e;}}
  private parseRelation(i:unknown):AssetRelationInput{try{return assetRelationInputSchema.parse(i);}catch(e){if(e instanceof ZodError)throw validationError();throw e;}}
  private requirePermission(c:AssetRequestContext,p:string):void{if(!c.permissions.includes(p))throw forbiddenError();}
  private auditFor(a:Asset,c:AssetRequestContext,action:AssetAuditEntry["action"],occurredAt:Date,reason:string,origin:string):AssetAuditEntry{return{tenantId:c.tenantId,assetId:a.id,action,actorUserId:c.userId,version:a.version,correlationId:c.correlationId,occurredAt,reason,origin};}
}
